version: 1
kind: workflow
name: Default Workflow
description: Perform task-action work
jobs:
  steps:
    - name: Create a new feature branch
      uses: actions/create-branch.yaml
    - name: Development
      uses: actions/development.yaml
    - name: Test
      uses: actions/test.yaml
    - name: Commit the changes
      uses: actions/git-commit.yaml
    - name: Push the changes
      uses: actions/git-push.yaml
    - name: Create a pull request
      uses: actions/create-pull-request.yaml
    - name: Send a message to Slack
      uses: actions/send-message-slack.yaml
    - name: Task Done
      uses: actions/task-done.yaml
prompt: Perform tasks in steps order.
