# configs/development.yaml
# Configuration values used in development environment

version: 1.0

# API server configuration
api:
  baseURL: 'http://localhost:8000/api/v1'
  timeout: 5000 # 5 seconds

# Database configuration (development uses lightweight in-memory DB)
database:
  type: 'sqlite'
  path: ':memory:'

# Feature flags (enable new features only during development)
featureFlags:
  newDashboardLayout: true
  betaAnalyticsPage: true
  legacyReport: false

# Logging level
logging:
  level: 'DEBUG' # Detailed logs during development
